services:
  cloudflare-ddns:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "cloudflare-ddns"
    restart: always # ensure the container restarts automatically after host reboot
    environment:
      - CF_API=${CF_API_BASEURL}

      - API_KEY=${CLOUDFLARE_API_KEY}
      - API_KEY_FILE=${CLOUDFLARE_API_KEY_FILE:-}

      - SUBDOMAIN=${SUBDOMAIN:-@}
      - SUBDOMAIN_FILE=${SUBDOMAIN_FILE:-}

      - ZONE=${CLOUDFLARE_ZONE}

      - PROXIED=${PROXIED:-false}

      - RRTYPE=${RRTYPE:-A}
      - IP_TYPE=${IP_TYPE:-4}

      - DELETE_ON_STOP=${DELETE_ON_STOP:-false}
      - INTERFACE=${INTERFACE:-}
      - CUSTOM_LOOKUP_CMD=${CUSTOM_LOOKUP_CMD:-}
      - DNS_SERVER=${DNS_SERVER:-1.1.1.1}
      - CRON=${CRON:-@hourly}
      - PUID=1000
      - PGID=1000
      #- DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      #- TELEGRAM_WEBHOOK_URL=${WEBHOOK_URL:-}
