#!/command/with-contenv sh

. /app/cloudflare.sh #sourcing cloudflare script
. /config/cloudflare.conf # sourcing conf file generated previously (env vars)

DnsIpAddress=$(getDnsRecordIp $CF_ZONE_ID $CF_RECORD_ID)

if [ ! -z ${CUSTOM_LOOKUP_CMD+x} ]; then
  CurrentIpAddress=$(getCustomIpAddress)
elif [ ! -z ${INTERFACE+x} ]; then
  CurrentIpAddress=$(getLocalIpAddress)
else
  CurrentIpAddress=$(getPublicIpAddress)
fi

now=$(date '+%Y-%m-%d %H:%M:%S')

if [ "$DnsIpAddress" == "" ]; then
  echo "ERROR: Failed to determine DNS record $CF_RECORD_NAME ip address."
elif [ "$CurrentIpAddress" != "$DnsIpAddress" ]; then
  echo "$now: Updating CloudFlare DNS record $CF_RECORD_NAME from $DnsIpAddress to $CurrentIpAddress..."
  update=$(updateDnsRecord $CF_ZONE_ID $CF_RECORD_ID $CF_RECORD_NAME $CurrentIpAddress)

  if [ "$update" == "null" ]; then
    msg="$now: ERROR: Failed to update CloudFlare DNS record $CF_RECORD_NAME from $DnsIpAddress to $CurrentIpAddress"
    echo $msg
  else
    webhook -X POST --data "{\"content\": \"$CF_RECORD_NAME updated to $CurrentIpAddress\"}" "$WEBHOOK_URL"
    msg="$now: CloudFlare DNS record $CF_RECORD_NAME ($CurrentIpAddress) updated successfully."
    echo $msg
  fi
  
else
  msg="$now: No DNS update required for $CF_RECORD_NAME ($DnsIpAddress)."
fi
echo $msg

# For telegram bot

# Chat ID of the recipient

#URL="https://api.telegram.org/bot$TOKEN/sendMessage"

# curl -s -X POST $URL -d chat_id=$CHAT_ID -d text="$msg"
